{{- if .Values.seeds.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "railsk8s.fullname" . }}-migration
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "railsk8s.fullname" . }}-migration
    spec:
      restartPolicy: Never
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh"]
        args: ["-c", "bundle exec rake db:seeds"]
        env:
          {{- toYaml .Values.env | nindent 12 }}
{{- end }}